apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-nodejs.fullname" . }}
  labels:
    app: {{ include "hello-world-nodejs.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "hello-world-nodejs.name" . }}
